---
book_repo: pivotal-cf/docs-book-aws-service-broker
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:  
# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: aws/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-aws-services
  directory: aws-services
  subnav_template: aws-services-subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.4
    changelog_href: https://docs.pivotal.io/aws-services/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Service Broker for AWS
    search_placeholder: Search AWS Service Broker
    url_prefix: aws-services
    local_product_version: 1.4
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/aws-services/
        display_name: v1.4
